services:
  app:
    restart: unless-stopped
    image: node:alpine
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    container_name: rahil-app
    working_dir: /app
    volumes:
      - ./app:/app
    command: node server.js
    ports:
      - "3000:3000"

  app2:
    restart: unless-stopped
    image: node:alpine
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    container_name: rahil-app2
    working_dir: /app
    volumes:
      - ./app2:/app
    command: node server.js
    ports:
      - "3001:3001"

  nginx:
    restart: unless-stopped
    image: nginx:alpine
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    container_name: homelab-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - app2
